### ISSUE TITLE
[Suggestion] Force SSL encryption to databases/redis

### ISSUE THREAD

**Issue by joscdk** [vapor-cloud/roadmap#25]
To ensure a high level of security, as we are allowing for external connections to our databases, we could force encryption at transit to databases (MySQL, PostgreSQL and MariaDB), and to our Redis servers.

This would help our users give an extra boost of security to their apps.

If not forced, another way could be to make it an option if it should be forced or not.

**Comment by proggeramlug** [comment]
I'd recommend to enforce it no matter what. If there is ever any problem - and may it be ever so small - you have done the best in your ability to prevent it from happening.
