### ISSUE TITLE
[Feature Request | Discussion] Allow Swift Commands Before Build

### ISSUE THREAD

**Issue by calebkleveter** [vapor-cloud/roadmap#26]
It would be useful to allow running `swift` CLI commands before a project is built. For example, using [edited packages](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#editable-packages) doesn't work because when the project is built, there is no information in the `.build` directory about the package that should be edited. This would work if we just ran `swift package edit <PACKAGE>` before building.

Are there any thoughts on this?

**Comment by joscdk** [comment]
Depending on what is possible with SPM etc. Cloud 2 would allow for two ways to customize deployments.

1: Custom docker template, 100 % freedom in terms of what should run when.

2: Hooks that can be intercepted at various points in our Docker templates

If it's just a command that should be run, i guess both options above in theory could solve your problem
