### ISSUE TITLE
[Discussion][WIP] Statistics monitoring

### ISSUE THREAD

**Issue by joscdk** [vapor-cloud/roadmap#32]
## Web replica

The idea for web replica monitoring is to get insight into resource usage.

### History view

The following historical view are suggested, with the proposed resolution

| Past | Resolution |
| ---- | ----------- |
| 6 hours | 10 minutes |
| 24 hours | 10 minutes |
| 7 days | 2 hours |
| 30 days | 1 day |

### Proposed metrics

We suggest the following metrics

| Metric | Available | Alerting available |
| ------ | --------- | ----------------- |
| CPU Usage | Beta | Yes |
| Memory usage | Beta | Yes |
| Request count | Beta/GA | No |
| Events | Beta | No |

## Database metrics

Not planned yet

## Redis metrics

Not planned yet

**Comment by MrLotU** [comment]
You might already know about this, but a while back I built a vapor package on top of [SwiftMetrics](https://github.com/runtimetools/swiftmetrics) implementing metrics for vapor apps, can be seen in [vapor-community/VaporMonitoring](https://github.com/vapor-community/VaporMonitoring)

**Comment by joscdk** [comment]
@MrLotU yeah to limit the resource usage for collecting metrics, we collect it on the host level, and add the data to Prometheus. People are completely free to use the package in their replicas, but we have all the needed data in the Kubernetes layer of the system :)
