### ISSUE TITLE
New custom docker and and cloud.yml system

### ISSUE THREAD

**Issue by joscdk** [vapor-cloud/roadmap#35]
For Cloud 2 we will support multiple replicas, and custom Docker files. This will make a change for how we will handle building containers.

As Cloud 2 is still early, this is still work in progress and can change with time.

## cloud.yml file

In cloud 2 we will completely remove the cloud.yml file, as we can achieve the needed functionality without.

## Multiple replicas

In Cloud 2 it will be possible to have multiple replicas running with different docker templates, per default all applications will have a **web** replica, which is the default for running the application. Other types could be offloading large tasks to a queue replica. More information on this system will be added during the beta phase.

## Custom docker files

Per default Cloud 2 will always use the latest Swift release to build the project.

All Vapor templates will be updated to include a Dockerfile that will be used during build. If a different Swift version is required, people will need to add a different Dockerfile to their projects.

The Dockerfile naming should be like this:
```
<replicaName>.Dockerfile
```
For example
```
web.Dockerfile
```

Per default all docker files will automatically be loaded on port 80, so all Vapor apps will be set to use port 80 instead of 8080. A different port can be set from the dashboard on the replica settings once we release multiple replicas in the beta.

**Comment by Cellane** [comment]
Maybe others would disagree but I’d think a bit more about the `Dockerfile` naming template, and propose `Dockerfile.cloud.<replicaName>` as an alternative.

The reasoning for this change being that some of my projects already contain quite a few `Dockerfile`s and I have found it helpful to name them all with `Dockerfile` prefix just to keep them nicely clumped together in directory listing. That way `Dockerfile.dev`, `Dockerfile.test` and `Dockerfile.prod` are grouped right next to each other, as opposed to having for example `dev.Dockerfile`/`test.Dockerfile`/`prod.Dockerfile` mixed with other project files.

**Comment by joscdk** [comment]
@Cellane i get your reasoning. The reason for <replicaName>.Dockerfile is that at least in VSCode with the official Docker package you don't get syntax highlight etc. With e.g. Dockerfile.web

It would still not read e.g. Dockerfile it would only read `replicaName.Dockerfile` .. e.g. `web.Dockerfile`

**Comment by joscdk** [comment]
<img width="1630" alt="screen shot 2018-09-19 at 10 41 39 am" src="https://user-images.githubusercontent.com/2535140/45741730-9de34180-bbf8-11e8-9980-7acca2556b7d.png">

**Comment by Cellane** [comment]
@joscdk I see, I didn’t realize that VSCode recognizes `<something>.Dockerfile`. Apparently, both `<something>.Dockerfile` and `Dockerfile.<something>` worked in the past (Microsoft/vscode#38797), there have been attempts to fix it again (Microsoft/vscode-docker#214) but at this moment, it’s only fixable with user-level configuration change (Microsoft/vscode-docker#192). Sigh.

**Comment by joscdk** [comment]
@Cellane i see, we started to look a lot of places, and looked like from what we could see that <something>.Dockerfile was the more recognized :)

Besides that, it shouldn't be that big a problem with conflict as we see it, as the Dockerfile used for vapor cloud should just be any kind of production ready Dockerfile that can build and run the project, the ones used for Vapor Cloud don't require anything special setup, as long as it can build and run the project :) .. So it's not necessarily only for Vapor Cloud :)
